# -*- coding: utf-8 -*-
"""Lab4_Q2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBT7W2FiYAWxxp9IuTc1aQV4TkpT5FjS
"""

points = [(5, 2), (3, 8), (4, 4), (3, 9), (25, 5), (10, 1), (2, 4), (9, 3)]

# a.สลับค่าจาก (x, y) เป็น (y, x) สําหรับทุกคู่อันดับ
# [ expression for item in iterable ] "ทำสิ่งนี้... กับทุกตัว... ในลิสต์นั้น"
# Python รู้ว่าแต่ละ element ใน points เป็น tuple จึง “แกะ” ค่าออกอัตโนมัติ
"""
✔ points[i] คือ tuple ลำดับที่ i
✔ point[0] = ค่าแรก
✔ point[1] = ค่าที่สอง
✔ (point[1], point[0]) = สลับตำแหน่ง

index 0
points[0] = (5, 2)
(point[1], point[0]) → (2, 5)

index 1
points[1] = (3, 8)
(point[1], point[0]) → (8, 3)

a = [(point[1], point[0]) for point in points] ได้เหมือนกัน
a = [p[::-1] for p in points] เป็นการย้อนกลับ
"""
a =  [(y, x) for (x, y) in points]
print("a. สลับค่า (x, y) → (y, x):\n",a)

# b. เลือกคู่อันดับ (x,y) โดยที่ x มีค่ามากกว่า y
# [ expression for item in iterable if condition ] "Expression จะทำงานก็ต่อเมื่อ Condition เป็น True เท่านั้น"
b = [(x, y) for (x, y) in points if x > y]
print("b. เลือกคู่อันดับที่ x > y:\n",b)

# c. เลือกคู่อันดับ (x,y) โดยที่ x มีค่าน้อยกว่า y
c = [(x, y) for (x, y) in points if x < y]
print("c. เลือกคู่อันดับที่ x < y:\n",c)

# d. เลือกคู่อันดับ (x,y) โดยที่ x มีค่าเท่ากับ y
d = [(x, y) for (x, y) in points if x == y]
print("d. เลือกคู่อันดับที่ x = y:\n",d)

# e. เลือกคู่อันดับ (x,y) โดยที่ x^2=y
e = [(x, y) for (x, y) in points if x**2 == y]
print("e. เลือกคู่อันดับที่ x² = y:\n",e)

# f. เลือกคู่อันดับ (x,y) โดยที่ y^2=x
f = [(x, y) for (x, y) in points if y**2 == x]
print("f. เลือกคู่อันดับที่ y² = x\n",f)

print("Original Data: ",points)
print("a. Swapped (y, x):",a)
print("b. Where x > y:",b)
print("c. Where x < y:",c)
print("d. Where x = y:",d)
print("e. Where x² = y:",e)
print("f. Where y² = x",f)