# -*- coding: utf-8 -*-
"""Lab4_Q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu8DFZaD4baZMGpW1R5yQ5hC1baiL_pe
"""

card = input("Please enter the cards in the deck (separated by spaces): ").upper().split()
command = input("Please enter the command (e.g. ,CSCS): ").upper()

for cmd in command:
    mid = len(card) // 2 # ใช้ // เพื่อให้เป็น int

    # ----- CUT -----
    if cmd == 'C':
        first = card[:mid]
        second = card[mid:]
        card = second + first   # ⭐ อัปเดต card เพราะถ้าไม่อัปตอนเอาไปทำต่อค่ามันจะเป็นค่าเดิม

    # ----- SHUFFLE (กรีดไพ่) -----
    elif cmd == 'S':
        left = card[:mid]
        right = card[mid:]
        result = []

        for i in range(mid):
            result.append(left[i])
            result.append(right[i])

        card = result            # ⭐ อัปเดต card

print("The final state of the deck:", " ".join(card))
# ตัวคั่น.join(ข้อมูลที่เป็น list หรือ tuple)
"""
card = ['7', 'A', '8', '2']
print(" ".join(card))
result => 7 A 8 2
"""